#ifndef CFS_EVS_VERIFIER_H
#define CFS_EVS_VERIFIER_H

/* Generated by flatcc 0.6.0-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef CFS_EVS_READER_H
#include "cfs_evs_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int cFSEVS_Test_SendEvent_verify_table(flatcc_table_verifier_descriptor_t *td);

static int cFSEVS_Test_SendEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* EventID */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* EventType */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* Spec */)) return ret;
    return flatcc_verify_ok;
}

static inline int cFSEVS_Test_SendEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, cFSEVS_Test_SendEvent_identifier, &cFSEVS_Test_SendEvent_verify_table);
}

static inline int cFSEVS_Test_SendEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, cFSEVS_Test_SendEvent_type_identifier, &cFSEVS_Test_SendEvent_verify_table);
}

static inline int cFSEVS_Test_SendEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &cFSEVS_Test_SendEvent_verify_table);
}

static inline int cFSEVS_Test_SendEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &cFSEVS_Test_SendEvent_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* CFS_EVS_VERIFIER_H */
