#ifndef CFS_EVS_READER_H
#define CFS_EVS_READER_H

/* Generated by flatcc 0.6.0-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct cFSEVS_Test_SendEvent_table *cFSEVS_Test_SendEvent_table_t;
typedef struct cFSEVS_Test_SendEvent_table *cFSEVS_Test_SendEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *cFSEVS_Test_SendEvent_vec_t;
typedef flatbuffers_uoffset_t *cFSEVS_Test_SendEvent_mutable_vec_t;
#ifndef cFSEVS_Test_SendEvent_identifier
#define cFSEVS_Test_SendEvent_identifier flatbuffers_identifier
#endif
#define cFSEVS_Test_SendEvent_type_hash ((flatbuffers_thash_t)0xd1621cb3)
#define cFSEVS_Test_SendEvent_type_identifier "\xb3\x1c\x62\xd1"



struct cFSEVS_Test_SendEvent_table { uint8_t unused__; };

static inline size_t cFSEVS_Test_SendEvent_vec_len(cFSEVS_Test_SendEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline cFSEVS_Test_SendEvent_table_t cFSEVS_Test_SendEvent_vec_at(cFSEVS_Test_SendEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(cFSEVS_Test_SendEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(cFSEVS_Test_SendEvent)

__flatbuffers_define_scalar_field(0, cFSEVS_Test_SendEvent, EventID, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, cFSEVS_Test_SendEvent, EventType, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(2, cFSEVS_Test_SendEvent, Spec, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* CFS_EVS_READER_H */
