#ifndef CFS_EVS_BUILDER_H
#define CFS_EVS_BUILDER_H

/* Generated by flatcc 0.6.0-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef CFS_EVS_READER_H
#include "cfs_evs_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

static const flatbuffers_voffset_t __cFSEVS_Test_SendEvent_required[] = { 0 };
typedef flatbuffers_ref_t cFSEVS_Test_SendEvent_ref_t;
static cFSEVS_Test_SendEvent_ref_t cFSEVS_Test_SendEvent_clone(flatbuffers_builder_t *B, cFSEVS_Test_SendEvent_table_t t);
__flatbuffers_build_table(flatbuffers_, cFSEVS_Test_SendEvent, 3)

#define __cFSEVS_Test_SendEvent_formal_args , uint16_t v0, uint16_t v1, flatbuffers_string_ref_t v2
#define __cFSEVS_Test_SendEvent_call_args , v0, v1, v2
static inline cFSEVS_Test_SendEvent_ref_t cFSEVS_Test_SendEvent_create(flatbuffers_builder_t *B __cFSEVS_Test_SendEvent_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, cFSEVS_Test_SendEvent, cFSEVS_Test_SendEvent_identifier, cFSEVS_Test_SendEvent_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, cFSEVS_Test_SendEvent_EventID, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), cFSEVS_Test_SendEvent)
__flatbuffers_build_scalar_field(1, flatbuffers_, cFSEVS_Test_SendEvent_EventType, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), cFSEVS_Test_SendEvent)
__flatbuffers_build_string_field(2, flatbuffers_, cFSEVS_Test_SendEvent_Spec, cFSEVS_Test_SendEvent)

static inline cFSEVS_Test_SendEvent_ref_t cFSEVS_Test_SendEvent_create(flatbuffers_builder_t *B __cFSEVS_Test_SendEvent_formal_args)
{
    if (cFSEVS_Test_SendEvent_start(B)
        || cFSEVS_Test_SendEvent_Spec_add(B, v2)
        || cFSEVS_Test_SendEvent_EventID_add(B, v0)
        || cFSEVS_Test_SendEvent_EventType_add(B, v1)) {
        return 0;
    }
    return cFSEVS_Test_SendEvent_end(B);
}

static cFSEVS_Test_SendEvent_ref_t cFSEVS_Test_SendEvent_clone(flatbuffers_builder_t *B, cFSEVS_Test_SendEvent_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (cFSEVS_Test_SendEvent_start(B)
        || cFSEVS_Test_SendEvent_Spec_pick(B, t)
        || cFSEVS_Test_SendEvent_EventID_pick(B, t)
        || cFSEVS_Test_SendEvent_EventType_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, cFSEVS_Test_SendEvent_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* CFS_EVS_BUILDER_H */
