import sys 
import ConfigParser

results_name = "results.txt"
folder_name = "test1"
# Parameters that have multiple values
maps = (#"./bitmaps/grid_18.png",
        "./bitmaps/grid_36.png",
        "./bitmaps/grid_54.png",
        "./bitmaps/grid_72.png") #,
        #"./bitmaps/grid_90.png")
speedups = (2, 4)#("1", "2", "4", "8")

# The default parameters
config = ConfigParser.RawConfigParser()

config.add_section("files")
config.set("files", "cfg", "./configs/single_comp.cfg")
config.set("files", "world", "./worlds/single_comp.world")
config.set("files", "map", "SET_THIS")

config.add_section("controllers")
config.set("controllers", "num", "1") # Should probably fix this
config.set("controllers", "cont0", "wave")
config.set("controllers", "name0", "hank")

config.add_section("experiment")
config.set("experiment", "runs", "3")
config.set("experiment", "timeout", "180")

config.add_section("worldfile")
config.set("worldfile", "speedup", "SET_THIS")


# Make all of the .ini files
count = 0
for i in range(0, len(speedups)):
    config.set("worldfile", "speedup", speedups[i])
    for j in range(0, len(maps)):
        config.set("files", "map", maps[j])
        new_file = open("conf_" + str(count) + ".ini", "w")
        config.write(new_file)
        count = count + 1


# Make a file "run_set.sh"
bash_script = open("run_set.sh", "w")
bash_script.write("#!/bin/bash\n\n")
bash_script.write("# Generated by script_gen.py\n\n")

count = 0
for i in range(0, len(speedups)):
    for j in range(0, len(maps)):
        bash_script.write("echo \"" + str(count) + " Experiment: ############################\"\n")
        bash_script.write("python overlord.py ./experiments/" + folder_name + "/conf_" + str(count) + ".ini " + results_name + "\n\n")
        count = count + 1



