[package]
name = "compare_bytes"
version = "0.1.0"
authors = ["Marshall, James 459937851 <james.marshall-1@nasa.gov>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
