#!/bin/sh 
# 
# Pulled from http://en.wikibooks.org/wiki/QEMU/Networking
#
# Script to bring down and delete bridge br0 when QEMU exits 
# 
# Bring down eth0 and br0 
#
ifconfig eth0 down
ifconfig br0 down
# 
# Delete the bridge
#
brctl delbr br0 
# 
# bring up eth0 in "normal" mode 
#
ifconfig eth0 -promisc
ifconfig eth0 up
#
# delete the tap device
#
openvpn --rmtun --dev $1
#
# start firewall again
# 
#/sbin/service firestarter start 